#!/usr/bin/env bash

set -euo pipefail

default_install_dir="/usr/local/bin"
install_dir=$default_install_dir
install_dir_opt=${1:-}
if [ "$install_dir_opt" ]; then
    install_dir="$install_dir_opt"
fi

download_dir=/tmp

latest_release="$(curl -sL https://raw.githubusercontent.com/borkdude/jet/master/resources/JET_RELEASED_VERSION)"

case "$(uname -s)" in
    Linux*)     platform=linux;;
    Darwin*)    platform=macos;;
esac

download_url="https://github.com/borkdude/jet/releases/download/v$latest_release/jet-$latest_release-$platform-amd64.tar.gz"
download_file="jet-$latest_release-$platform-amd64.tar.gz"

cd "$download_dir"
echo -e "Downloading $download_url."
curl -o "$download_file" -sL "$download_url"
tar -xzf "$download_file"
rm "$download_file"

cd "$install_dir"
if [ -f jet ]; then
    echo "Moving $install_dir/jet to $install_dir/jet.old"
fi

mv -f "$download_dir/jet" "$PWD/jet"

echo "Successfully installed jet in $install_dir."
