#!/usr/bin/env bash

set -eo pipefail

rm -rf /tmp/release
mkdir -p /tmp/release
cp jet /tmp/release
VERSION=$(cat resources/JET_VERSION)

# release jar, adapted from https://github.com/clj-kondo/clj-kondo/blob/master/.circleci/script/release

if [[ "$JET_PLATFORM" = "linux" ]]; then
    lein with-profiles +clojure-1.10.3 do clean, uberjar
    jar="target/jet-$VERSION-standalone.jar"
    cp "$jar" /tmp/release
fi

pushd /tmp/release

## release binary as zip archive

arch=${JET_ARCH:-amd64}

archive="jet-$VERSION-$JET_PLATFORM-$arch.tar.gz"

tar zcvf "$archive" jet
## cleanup

rm jet

popd

bb release-artifact "/tmp/release/$archive" || true
