#!/usr/bin/env bash

set -eo pipefail

if [ -z "$GRAALVM_HOME" ]; then
    echo "Please set GRAALVM_HOME"
    exit 1
fi

"$GRAALVM_HOME/bin/gu" install native-image || true

JET_VERSION=$(cat resources/JET_VERSION)

lein with-profiles +clojure-1.10.3 do clean, uberjar

$GRAALVM_HOME/bin/native-image \
  -jar target/jet-$JET_VERSION-standalone.jar \
  -H:+ReportExceptionStackTraces \
  --verbose \
  --no-fallback \
  "-J-Xmx3g"

lein clean
