#!/usr/bin/env bash

set -eo pipefail

if [ -z "$GRAALVM_HOME" ]; then
    echo "Please set GRAALVM_HOME"
    exit 1
fi

"$GRAALVM_HOME/bin/gu" install native-image || true

JET_VERSION=$(cat resources/JET_VERSION)

lein with-profiles +clojure-1.10.3 "do" clean, uberjar

BABASHKA_STATIC=${BABASHKA_STATIC:-}
BABASHKA_MUSL=${BABASHKA_MUSL:-}

args=("-jar" "target/jet-$JET_VERSION-standalone.jar"
      "-H:+ReportExceptionStackTraces"
      "--verbose"
      "--no-fallback"
      "--no-server"
      "-J-Xmx3g"
)

if [ "$BABASHKA_STATIC" = "true" ]; then
    args+=("--static")
    if [ "$BABASHKA_MUSL" = "true" ]; then
        args+=("--libc=musl"
               # see https://github.com/oracle/graal/issues/3398
               "-H:CCompilerOption=-Wl,-z,stack-size=2097152")
    else
        # see https://github.com/oracle/graal/issues/3737
        args+=("-H:+StaticExecutableWithDynamicLibC")
    fi
fi

"$GRAALVM_HOME/bin/native-image" "${args[@]}"

lein clean
