#!/usr/bin/env bash

set -eo pipefail

if [ -z "$GRAALVM_HOME" ]; then
    echo "Please set GRAALVM_HOME"
    exit 1
fi

JET_VERSION=$(cat resources/JET_VERSION)

export PATH=$GRAALVM_HOME/bin:$PATH
export JAVA_HOME=$GRAALVM_HOME

lein with-profiles +native-image "do" clean, uberjar

BABASHKA_STATIC=${BABASHKA_STATIC:-}
BABASHKA_MUSL=${BABASHKA_MUSL:-}

args=("-jar" "target/jet-$JET_VERSION-standalone.jar"
      "-H:+ReportExceptionStackTraces"
      "--verbose"
      "--no-fallback"
      "-J-Xmx3g"
      "-J-Djet.native=true")

if [ "$BABASHKA_STATIC" = "true" ]; then
    if [ "$BABASHKA_MUSL" = "true" ]; then
        args+=("--static"
               "--libc=musl"
               # see https://github.com/oracle/graal/issues/3398
               "-H:CCompilerOption=-Wl,-z,stack-size=2097152")
    else
        # see https://github.com/oracle/graal/issues/3737
        args+=("-H:+UnlockExperimentalVMOptions"
               "-H:+StaticExecutableWithDynamicLibC")
    fi
fi

detected_graalvm_version=$("$GRAALVM_HOME/bin/native-image" "--version")

if [[ $detected_graalvm_version == native-image\ 25* ]]; then
    args+=("--future-defaults=all")
fi

"$GRAALVM_HOME/bin/native-image" "${args[@]}"

lein clean
